### ISSUE TITLE
Error `'version' must be defined globally`

### ISSUE THREAD

**Issue by gegnew** [sayanarijit/gh-xplr#2]
After a fresh install, when I try to run the example (or to run `gh xplr` for any repo), I get:

`| ERROR | 'version' must be defined globally in /tmp/gh-xplr.1666002657459/.git/xplr.lua`

**Comment by sayanarijit** [comment]
Thanks for reporting. Fixed in [v0.1.11](https://github.com/sayanarijit/gh-xplr/releases/tag/v0.1.11)
